/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
  @Test
  public void appHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull("app should have a greeting", classUnderTest.getGreeting());
  }

  @Test
  public void testAppReternHelloWorld() {
    App classUnderTest = new App();
    assertEquals("Hello World!", classUnderTest.getGreeting());
  }

  @Test
  public void Sum() {
    App calculate = new App();
    int expected = 5;
    assertEquals(expected, calculate.sum(2, 3));
  }

  @Test
  public void Ave() {
    App calculate = new App();
    double expected = 2.5;
    assertEquals(expected, calculate.ave(5), 0);
  }

  @Test
  public void Sum2() {
    App calculate = new App();
    int expected = 55;
    assertEquals(expected, calculate.sum2(1, 10));
  }

  @Test
  public void Ave2() {
    App calculate = new App();
    double expected = 5.5;
    assertEquals(expected, calculate.ave2(1, 10), 0);
  }

  @Test
  public void Sumodd() {
    App calculate = new App();
    int expected = 25;
    assertEquals(expected, calculate.sumodd(1, 10));
  }

  @Test
  public void Sumeven() {
    App calculate = new App();
    int expected = 30;
    assertEquals(expected, calculate.sumeven(1, 10));
  }
}
